Script started on 2015年03月14日 (週六) 22時56分53秒
]0;F74034033@2015cpp: ~F74034033@2015cpp:~$ git clone https://github.com/joanelsefde/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[K[3Pwhoami;pwd[5P./a.hwhoami;pwd
F74034033
/home/F74034033
]0;F74034033@2015cpp: ~F74034033@2015cpp:~$ whoami;pwdgit clone https://github.com/joanelsefde/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[K
user.name=joanelsefde
user.email=F74034033@mail.ncku.edu.tw
]0;F74034033@2015cpp: ~F74034033@2015cpp:~$ git config -l[3Pwhoami;pwdgit clone https://github.com/joanelsefde/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;F74034033@2015cpp: ~F74034033@2015cpp:~$ ./[K[Kg++ -o a.h A.cpp
g++: error: A.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
]0;F74034033@2015cpp: ~F74034033@2015cpp:~$ cd lab1
]0;F74034033@2015cpp: ~/lab1F74034033@2015cpp:~/lab1$ cd lab1g++ -o a.h A.cpp
]0;F74034033@2015cpp: ~/lab1F74034033@2015cpp:~/lab1$ ./A[Ka.h
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 ]0;F74034033@2015cpp: ~/lab1F74034033@2015cpp:~/lab1$ exit

Script done on 2015年03月14日 (週六) 22時57分45秒
